version: '3.4'
services:
  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: raf_cloud_db
      MYSQL_ROOT_PASSWORD: root
    # volumes:
      # - db-data:/var/lib/mysql